/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PracticeResultRouteImport } from './routes/practice_.result'
import { Route as PracticePlayRouteImport } from './routes/practice_.play'

const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeResultRoute = PracticeResultRouteImport.update({
  id: '/practice_/result',
  path: '/practice/result',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticePlayRoute = PracticePlayRouteImport.update({
  id: '/practice_/play',
  path: '/practice/play',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/practice': typeof PracticeRoute
  '/practice/play': typeof PracticePlayRoute
  '/practice/result': typeof PracticeResultRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/practice': typeof PracticeRoute
  '/practice/play': typeof PracticePlayRoute
  '/practice/result': typeof PracticeResultRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/practice': typeof PracticeRoute
  '/practice_/play': typeof PracticePlayRoute
  '/practice_/result': typeof PracticeResultRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/practice'
    | '/practice/play'
    | '/practice/result'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/practice' | '/practice/play' | '/practice/result'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/practice'
    | '/practice_/play'
    | '/practice_/result'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  PracticeRoute: typeof PracticeRoute
  PracticePlayRoute: typeof PracticePlayRoute
  PracticeResultRoute: typeof PracticeResultRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice_/result': {
      id: '/practice_/result'
      path: '/practice/result'
      fullPath: '/practice/result'
      preLoaderRoute: typeof PracticeResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice_/play': {
      id: '/practice_/play'
      path: '/practice/play'
      fullPath: '/practice/play'
      preLoaderRoute: typeof PracticePlayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  PracticeRoute: PracticeRoute,
  PracticePlayRoute: PracticePlayRoute,
  PracticeResultRoute: PracticeResultRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
